"""Test environment detection shared by the test platform, `./reason ci`, and the tests.

Every environment-dependent decision lives here so Local, `./reason ci`, and GitHub
Actions cannot drift apart (CI Test Consistency / Environment Parity v0.1):

* the repository is identified by its *contents*, never by its checkout directory name;
* a missing declared dependency is a local SKIP but a CI FAIL, with a message that says
  what to run.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import unittest
from collections.abc import Mapping
from pathlib import Path

# A directory is the ReasonScript repository when all of these exist in it.
REPO_MARKERS = ("frontend", "toolchain", "ReasonRuntime")

VSCODE_EXTENSION = "vscode-extension"

SKIP_VSCODE_DEPENDENCIES = (
    "SKIPPED: vscode-extension/node_modules not found.\n"
    "Run `npm ci` in vscode-extension to enable this local test."
)
FAIL_VSCODE_DEPENDENCIES = (
    "FAILED: CI requires vscode-extension/node_modules.\n"
    "The workflow must run `npm ci` before the Test job."
)

# Tests that must have executed (passed) in a CI run of the full test plan.
CI_REQUIRED_TESTS = {
    "vscode-extension-typescript": (
        "tests/lsp/test_vscode_extension_contract.py::test_vscode_extension_typescript_compiles_cleanly"
    ),
    "vscode-extension-dependencies": (
        "vscode_extension_phase1_4_tests/test_vscode_extension_phase1_4.py::"
        "VSCodeExtensionPhase14Tests::test_vsxp14_003_dependency_presence"
    ),
}


def rust_toolchain() -> tuple[bool, str]:
    """Whether the complete core Rust toolchain is available, plus version evidence."""
    versions = []
    for command in ("rustc", "cargo"):
        if shutil.which(command) is None:
            return False, f"{command} not found"
        completed = subprocess.run(
            [command, "--version"], text=True, capture_output=True, check=False
        )
        if completed.returncode != 0:
            return False, f"{command} --version failed"
        versions.append(completed.stdout.strip())
    return True, "; ".join(versions)


def is_ci(env: Mapping[str, str] | None = None) -> bool:
    """True under GitHub Actions and any runner that sets `CI` (`CI=0` / `false` is not CI)."""
    value = (os.environ if env is None else env).get("CI", "").strip().lower()
    return value not in ("", "0", "false", "no", "off")


def is_reasonscript_repo_root(path: Path) -> bool:
    return all((Path(path) / marker).is_dir() for marker in REPO_MARKERS)


def find_repo_root(start: Path | None = None) -> Path:
    """The nearest ancestor of `start` (default: this file) that is the repository root.

    Markers only: it works in renamed clones, `git worktree`s, fork checkouts, and source
    archives without a `.git` directory.
    """
    origin = Path(start if start is not None else __file__).resolve()
    for candidate in (origin, *origin.parents):
        if is_reasonscript_repo_root(candidate):
            return candidate
    raise FileNotFoundError(f"no ReasonScript repository root (markers {REPO_MARKERS}) above {origin}")


def vscode_extension_dir(root: Path | None = None) -> Path:
    return (find_repo_root() if root is None else Path(root)) / VSCODE_EXTENSION


def has_vscode_dependencies(root: Path | None = None) -> bool:
    """`node_modules` is generated by `npm ci`; it is a test dependency, not a repository artifact."""
    return (vscode_extension_dir(root) / "node_modules").is_dir()


def vscode_dependency_action(
    root: Path | None = None, env: Mapping[str, str] | None = None
) -> tuple[str, str]:
    """`("run" | "skip" | "fail", message)` for a test that needs the extension's dependencies."""
    if has_vscode_dependencies(root):
        return "run", ""
    if is_ci(env):
        return "fail", FAIL_VSCODE_DEPENDENCIES
    return "skip", SKIP_VSCODE_DEPENDENCIES


def require_vscode_dependencies(root: Path | None = None, env: Mapping[str, str] | None = None) -> None:
    """Call first in a test that needs `vscode-extension/node_modules`.

    Locally the test skips with the reason; under CI a missing dependency fails it.
    """
    action, message = vscode_dependency_action(root, env)
    if action == "skip":
        raise unittest.SkipTest(message)
    if action == "fail":
        raise AssertionError(message)
